---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    name: "cosolicitudoriquery"
  name: "cosolicitudoriquery"
  namespace: "foh"
spec:
  ports:
  - name: "http"
    port: 8080
    protocol: "TCP"
    targetPort: 8080
  selector:
    name: "cosolicitudoriquery"
  type: "NodePort"
