---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    name: "cosolicitudoriquery"
  name: "cosolicitudoriquery"
  namespace: "foh"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "cosolicitudoriquery"
  template:
    metadata:
      labels:
        name: "cosolicitudoriquery"
    spec:
      containers:
      - env:
        - name: "ENV"
          value: "dev"
        - name: "PORT"
          value: "8080"
        - name: "BASE_LOGS"
          value: "/logs"
        - name: "LOG_LEVEL_SERVICE"
          value: "INFO"
        - name: "LOG_OUTPUT_SERVICE"
          value: "AMQP"
        - name: "DS_FULXG01_URL"
          valueFrom:
            configMapKeyRef:
              key: "DS_FULXG01_URL"
              name: "config-cosolicitudoriquery"
        - name: "ESBS_USR"
          valueFrom:
            secretKeyRef:
              key: "ESBS_USR"
              name: "secret-cosolicitudoriquery"
        - name: "ESBS_PWD"
          valueFrom:
            secretKeyRef:
              key: "ESBS_PWD"
              name: "secret-cosolicitudoriquery"
        - name: "RABBITMQ_TRANSACTION_HOST"
          valueFrom:
            secretKeyRef:
              key: "RABBITMQ_TRANSACTION_HOST"
              name: "rabbitmq-cred"
        - name: "RABBITMQ_TRANSACTION_PORT"
          valueFrom:
            secretKeyRef:
              key: "RABBITMQ_TRANSACTION_PORT"
              name: "rabbitmq-cred"
        - name: "RABBITMQ_TRANSACTION_USR"
          valueFrom:
            secretKeyRef:
              key: "RABBITMQ_TRANSACTION_USR"
              name: "rabbitmq-cred"
        - name: "RABBITMQ_TRANSACTION_PWD"
          valueFrom:
            secretKeyRef:
              key: "RABBITMQ_TRANSACTION_PWD"
              name: "rabbitmq-cred"
        image: "us-central1-docker.pkg.dev/foh-gke-des/foh-docker-dev/cosolicitudoriquery:latest"
        name: "cosolicitudoriquery"
        ports:
        - containerPort: 8080
          protocol: "TCP"
        resources:
          limits:
            cpu: "500m"
            memory: "900Mi"
          requests:
            cpu: "10m"
            memory: "10Mi"
        volumeMounts:
        - mountPath: "/etc/ssl/certs/gkefoh.pfx"
          name: "secret-volume"
          readOnly: true
          subPath: "gkefoh.pfx"
      - args:
        - "--credentials-file=/secrets/service_account.json"
        - "--psc"
        - "projects/foh-gke-des/locations/us-central1/clusters/fohcls0r4d/instances/fohctr23d"
        - "--port=5432"
        command:
        - "/alloydb-auth-proxy"
        image: "us-central1-docker.pkg.dev/foh-gke-des/foh-docker-dev/fohalloydbproxy:latest"
        name: "alloydb-proxy"
        resources:
          requests:
            cpu: "10m"
            memory: "10Mi"
        volumeMounts:
        - mountPath: "/secrets"
          name: "secret-volume1"
          readOnly: true
      volumes:
      - name: "secret-volume1"
        secret:
          defaultMode: 420
          secretName: "gke-client-sql-fohct23"
      - name: "secret-volume"
        secret:
          defaultMode: 420
          secretName: "gkefinancieraoh-local-secret"
